Repository netblue30/firejail, pull requests merged in 2025-01, with the labels that each got.

#6598 bugfix: fix possible memory leak in fs_home.c
  src/firejail/fs_home.c
Labels: bugfix

#6605 modif: clarify error messages in profile.c
  src/firejail/profile.c
Labels: enhancement

#6592 feature: build: add --disable-sandbox-check configure flag
  config.mk.in
  configure
  configure.ac
  src/firejail/checkcfg.c
  src/firejail/main.c
Labels: enhancement

#6607 docs: github: add program name/version to bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#6581 profiles: anki: fix dark mode detection & misc changes
  etc/profile-a-l/anki.profile
Labels: bugfix

#6624 docs(SECURITY.md): update distributions table & add note
  SECURITY.md
Labels: documentation

#6627 ci: check-c: run all checks in parallel mode
  .github/workflows/check-c.yml
Labels: enhancement
